if: branch = master
env:
  - HUGO_VERSION=0.40.2  # Hugo version from https://github.com/gohugoio/hugo/releases
language: minimal
git:
  depth: 1
  submodules_depth: 1
install:
  - gem install sass
  - wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mkdir /tmp/hugo
  - tar -xzf /tmp/hugo.tar.gz -C /tmp/hugo
  - export PATH=/tmp/hugo:$PATH
script:
  - bash tools/build.sh
deploy:
  - provider: pages
    repo: biodranik/alex.bio
    fqdn: alex.bio
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
