if: branch = master
language: node_js # npm is needed to install postcss-cli
node_js:
  - "10.9.0"
git:
  depth: 1
  submodules_depth: 1
before_install:
  - npm i -g npm@6.4.0
  # This workaround is required to avoid libstdc++ errors while running "extended" hugo with SASS support.
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
install:
  - npm install postcss-cli autoprefixer
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_extended_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo # From version 0.43 hugo automatically creates css files from sass/scss
deploy:
  - provider: pages
    repo: biodranik/alex.bio
    fqdn: alex.bio
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
after_deploy:
  - |
    # Clear CDN cache after production deployments.
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
        -H "X-Auth-Email: $X_AUTH_EMAIL" \
        -H "X-Auth-Key: $X_AUTH_KEY" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
      done
    fi
