if: branch = master
dist: xenial
sudo: required
env:
  global:
    - HUGO_RELEASE=0.76.3
language: node_js # npm is needed to install postcss-cli
node_js: "lts/*"
cache: npm
git:
  depth: 1
  submodules_depth: 1
install:
  - npm install postcss-cli autoprefixer
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb
script:
  - hugo # From version 0.43 hugo automatically creates css files from sass/scss
deploy:
  - provider: pages
    repo: biodranik/alex.bio
    fqdn: alex.bio
    target-branch: gh-pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure.
    keep-history: true
    on:
      branch: master
after_deploy:
  - |
    # Clear CDN cache after production deployments.
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
        -H "X-Auth-Email: $X_AUTH_EMAIL" \
        -H "X-Auth-Key: $X_AUTH_KEY" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
      done
    fi
