baseURL: https://alex.bio/
languageCode: en
defaultContentLanguage: en
title: "Alexander Borsuk: Software Engineer, MScEng, researcher, co-founder of VibroBox, cofounder of MAPS.ME"
disableKinds:
  ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
googleAnalytics: UA-71329020-1
copyright: © 2023 Alexander Borsuk, https://alex.bio/
# Updates .Page.Lastmod from git repo.
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  author: Alexander Borsuk
