baseURL: https://alex.bio/
languageCode: en-US
title: "Alexander Borsuk: Founding Investor @ VibroBox, cofounder @ MAPS.ME, Master of Applied Science"
disableKinds: ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
googleAnalytics: UA-71329020-1
Copyright: © 2018 Alexander Borsuk
