baseURL: https://alex.bio/
languageCode: en
defaultContentLanguage: en
title: "Alexander Borsuk: Software Engineer and researcher, co-founder of VibroBox, cofounder of MAPS.ME"
disableKinds: ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
googleAnalytics: UA-71329020-1
copyright: © 2018 Alexander Borsuk, https://alex.bio/

blackfriday:
  hrefTargetBlank: true
